server:
  port: 8081
  tomcat:
    max-swallow-size: -1
  servlet:
    context-path: /zylm
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

spring:
  banner:
    location: banner.txt